### PR TITLE
[RED & GREEN] Implement transaction history back end

### PR DESCRIPTION
**Pull request by ajierestus**
There are 2 commits included in this pull request. Each with a different purpose:
[RED] Create test for transaction history
[GREEN] Implement transaction history backend

### CODE REVIEW

**Review by joeladhika — APPROVED** [review]
Good job doing the transaction history feature !

**Review by azzuhripasaribu — APPROVED** [review]
All Good, well done on implementing TDD

**Comment by nichoje** [comment]
Looks good! Great job!

**Review by bryanttanujaya — APPROVED** [review]
Thank you for implementing the transaction history backend ajie! I will follow up on the front end

**Comment by athaqilmakarim** [comment]
Thank you for implementing the backend, good job!

**Review by athaqilmakarim — APPROVED** [review]
All clear thank you

**Pull request merged**
