### PR TITLE
Azzuhri - Fix Register CSS

### PR DESCRIPTION
**Pull request by azzuhripasaribu**
Fixed CSS of Register

### CODE REVIEW

**Review by bryanttanujaya — APPROVED** [review]
Hi Azzuhri! Thank you for repairing the CSS on the registration page. Now the page is great!

**Review by ajierestus — APPROVED** [review]
Hi Azzuhri, thanks for fixing the problem. The register page is looking good now because the CSS is integrated.

**Review by joeladhika — APPROVED** [review]
Thank you for fixing the CSS !

**Comment by nichoje** [comment]
Hi, Azzuhri! Thank you for the fix.

**Comment by athaqilmakarim** [comment]
Thank you for fixing the css!

**Pull request merged**
