### PR TITLE
[GREEN] Bryant - Implement Base for Cashier Backend

### PR DESCRIPTION
**Pull request by bryanttanujaya**
Bryant - Implement the cashier backend, Please review my code.

### CODE REVIEW

**Review by ajierestus — APPROVED** [review]
Good job Bryant, Keep it up!

**Review by azzuhripasaribu — APPROVED** [review]
Looks Good

**Review by joeladhika — APPROVED** [review]
Good Job!

**Comment by athaqilmakarim** [comment]
Thank you Bryant, good job!

**Pull request merged**
