### PR TITLE
Bryant

### PR DESCRIPTION
**Pull request by bryanttanujaya**
Bryant - Implement the User profile backend

### CODE REVIEW

**Comment by nichoje** [comment]
Hi, Bryant! Nice work overall. Thank you very much!

**Comment by bryanttanujaya** [comment]
Thank you for the comments guys! Appreciate that!

**Comment by ajierestus** [comment]
Hi Bryant, Really appreciate your work!

**Comment by azzuhripasaribu** [comment]
Good, remember  code cleanliness next time

**Pull request merged**
