### PR TITLE
Ajie - Implement frontend for navigation bar and edit profile

### PR DESCRIPTION
**Pull request by ajierestus**
Creating navigation bar and improving CSS for edit profile

### CODE REVIEW

**Review by azzuhripasaribu — APPROVED** [review]
Looks good

**Review by bryanttanujaya — APPROVED** [review]
I think your design is already good ajie keep up the good work!

**Review by joeladhika — APPROVED** [review]
Looks good, nice job!

**Review by athaqilmakarim — APPROVED** [review]
Great frontend implementation

**Comment by nichoje** [comment]
Thank you, Ajie. Great job and continue the good work!

**Pull request merged**
