### PR TITLE
[CHORES] Updating the Update Stock Frontend following the 15th PBI

### PR DESCRIPTION
**Pull request by bryanttanujaya**
I'm updating the Update Stock Frontend following the 15th PBI

### CODE REVIEW

**Review by ajierestus — APPROVED** [review]
Good job bryant

**Review by azzuhripasaribu — APPROVED** [review]
Looks Good, Well done!

**Review by joeladhika — APPROVED** [review]
Good job Bryant ! Thank You  !

**Comment by nichoje** [comment]
Great job, Bryant!

**Comment by athaqilmakarim** [comment]
Well implemented, keep up the good work

**Review by athaqilmakarim — APPROVED** [review]

**Pull request merged**
