### PR TITLE
[CHORES] Pbi 15 update stock front end

### PR DESCRIPTION
**Pull request by bryanttanujaya**
[CHORES] Updating the stock front end to obtain a better user experience

### CODE REVIEW

**Review by ajierestus — APPROVED** [review]
good job bryant!

**Comment by nichoje** [comment]
Good job! Thanks!

**Review by joeladhika — APPROVED** [review]
Nice Job!

**Review by athaqilmakarim — APPROVED** [review]
Good job, keep up!

**Review by azzuhripasaribu — APPROVED** [review]
Looks Good

**Pull request merged**
