### PR TITLE
Aqil - Implement frontend for menu list feature

### PR DESCRIPTION
**Pull request by athaqilmakarim**

### CODE REVIEW

**Comment by nichoje** [comment]
Nice add-ons, Aqil. Keep it up!

**Review by azzuhripasaribu — APPROVED** [review]
All fine, Great work!

**Review by joeladhika — APPROVED** [review]
Looks good !

**Review by ajierestus — APPROVED** [review]
What a cool design Aqil! Good job!

**Review by bryanttanujaya — APPROVED** [review]
Good Job Aqil! Thank you for implementing the menu list frontend

**Pull request merged**
