### PR TITLE
Implement transaction items details

### PR DESCRIPTION
**Pull request by azzuhripasaribu**
This feature shows user how many of each item has been sold

### CODE REVIEW

**Comment by nichoje** [comment]
Looks nice, please fix any bug that you have.

**Review by bryanttanujaya — APPROVED** [review]
Thank you Azzuhri for implementing the backend!

**Review by joeladhika — APPROVED** [review]
Nice but try to fix the Heroku!

**Review by ajierestus — APPROVED** [review]
Thank you for implementing the feature backend, Azzuhri!

**Pull request merged**
