### PR TITLE
[CHORES] Implement stock list and delete stock frontend

### PR DESCRIPTION
**Pull request by ajierestus**
[CHORES] Implement stock list and delete stock frontend

### CODE REVIEW

**Comment by nichoje** [comment]
Nice implementation, Ajie! Thanks!

**Review by joeladhika — APPROVED** [review]
Looks good ! good job ajie !

**Review by bryanttanujaya — APPROVED** [review]
Good Job and thank you Ajie for implementing and delete stock front end

**Review by azzuhripasaribu — APPROVED** [review]
Well done!, Thank you for implementing the frontend for delete stock.

**Pull request merged**
