### PR TITLE
[CHORES] Implement rought design for cashier page frontend

### PR DESCRIPTION
**Pull request by athaqilmakarim**

### CODE REVIEW

**Review by ajierestus — APPROVED** [review]
What a cool design, good job Aqil!

**Comment by nichoje** [comment]
Nice implementation, Aqil. Don’t forger to check for the error.

**Review by bryanttanujaya — APPROVED** [review]
You did great Aqil! Thank you for implementing the cashier frontend page

**Review by joeladhika — APPROVED** [review]
Nice, good job with the design!

**Pull request merged**
