### PR TITLE
Implement add menu backend feature

### PR DESCRIPTION
**Pull request by ajierestus**
Implement add menu backend feature and make some changes to related file

### CODE REVIEW

**Comment by athaqilmakarim** [comment]
Thank you, Ajie for implementing the backend for add menu feature!!

**Comment by nichoje** [comment]
Nice, Ajie! Keep progressing!

**Review by bryanttanujaya — APPROVED** [review]
Good Job Ajie on making the add menu backend!

**Review by joeladhika — APPROVED** [review]
Thank you for making the add menu feature!

**Pull request merged**
