### PR TITLE
[CHORES] Add stock frontend implementation

### PR DESCRIPTION
**Pull request by nichoje**

### CODE REVIEW

**Review by joeladhika — APPROVED** [review]
Nice job nichoo ! Thank you

**Review by ajierestus — APPROVED** [review]
Good job nicholas

**Review by bryanttanujaya — APPROVED** [review]
Good Job Nicholas! Thank you for implementing the frontend

**Review by azzuhripasaribu — APPROVED** [review]
Looks Good!, Thank you for implementing the frontend

**Pull request merged**
