### PR TITLE
Aqil - Implement rough design for menu list frontend feature

### PR DESCRIPTION
**Pull request by athaqilmakarim**

### CODE REVIEW

**Comment by nichoje** [comment]
Great job, Aqil! Keep it up!

**Review by joeladhika — APPROVED** [review]
Good job wih the front end ! it looks very nice

**Review by bryanttanujaya — APPROVED** [review]
Thank you Aqil for implementing the menu list front end! Good Job!

**Review by ajierestus — APPROVED** [review]
Good job, Aqil! You have create a good design!

**Pull request merged**
