### PR TITLE
[CHORES] Do revision for the add stock frontend 

### PR DESCRIPTION
**Pull request by ajierestus**
Creating better path for button in the add stock page and fixing typo in the pop up message

### CODE REVIEW

**Comment by nichoje** [comment]
Nice implementation, thank you.

**Review by joeladhika — APPROVED** [review]
Good Job !

**Comment by bryanttanujaya** [comment]
Good Job Ajie! thank you for doing the revision

**Review by athaqilmakarim — APPROVED** [review]
Good job, well implemented!

**Review by azzuhripasaribu — APPROVED** [review]
Great Job, Well done!

**Pull request merged**
