### PR TITLE
implement update stock

### PR DESCRIPTION
**Pull request by azzuhripasaribu**

### CODE REVIEW

**Review by ajierestus — APPROVED** [review]
Well done Azzuhri, you implement the feature really well!

**Comment by nichoje** [comment]
Good implementation, Azzuhri! Thanks.

**Comment by bryanttanujaya** [comment]
Thank you Azzuhri for implementing the Backend for the Update Stock feature, I will follow up by the Front End

**Comment by athaqilmakarim** [comment]
All good keep up the good work!

**Review by bryanttanujaya — APPROVED** [review]

**Pull request merged**
