### PR TITLE
Ajie - Implement javascript for sticky navbar

### PR DESCRIPTION
**Pull request by ajierestus**

### CODE REVIEW

**Comment by nichoje** [comment]
That's a great addition, Ajie! Great job!

**Review by bryanttanujaya — APPROVED** [review]
Thank you ajie for implementing sticky note for the navbar! Good Job!

**Review by athaqilmakarim — APPROVED** [review]
Thankyou Ajie

**Review by joeladhika — APPROVED** [review]
Good job with the sticky navbar!

**Review by azzuhripasaribu — APPROVED** [review]
Looks good

**Pull request merged**
